### PR TITLE
Add jsonnet helpers for front matter schema's

### PR DESCRIPTION
**Pull request by actualwitch**
# Description

this pr adds fiberplane-template helpers for adding front matter values

Implements [FP-3579](https://linear.app/fiberplane/issue/FP-3579/create-helper-jsonnet-functions-for-addfrontmatterschema)

# Checklist

- [x] The changes have been tested to be backwards compatible.
- [ ] The OpenAPI schema and generated client have been updated.
- [ ] New models module has been added to api generator xtask
- [x] New types/fields are [well-documented and annotated](/CONTRIBUTING.md#adding-types-and-their-annotations).
- [x] The CHANGELOG is updated.

> Please link any related PRs in other repositories that depend on this:

After merging, please merge related PRs ASAP, so others don't get blocked.

### CODE REVIEW

**Comment by brettimus** [comment]
out of curiosity - what's a good way to test this locally?  (how'd you test changes, do you have any templates you were working with?)

**Comment by actualwitch** [comment]
this pr includes a bunch of unit tests that can be run with `cargo test expand::tests::frontmatter_tests`, they check that helpers produce expected structs. to check on local studio i think using this branch should be enough, the templates from unit tests should work

**Review by hatchan — COMMENTED** [review]
Looks good already. But we should also support the array variants of the frontmatter values.

**Comment by actualwitch** [comment]
i added the multiple value support to string and user fields, it seems those are the only ones that support it

**Comment by hatchan** [comment]
> i added the multiple value support to string and user fields, it seems those are the only ones that support it

Are you sure that only string and user are supported? According to this list also number and date have support for it: https://github.com/fiberplane/fiberplane/blob/main/fiberplane-models/src/notebooks/front_matter.rs#L61-L79

**Comment by actualwitch** [comment]
i was going off the models that have `multiple`, but if these also support list form i can add 'em as well

**Review by hatchan — APPROVED** [review]

**Pull request merged**
